---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://ks888.github.io/hugo_trial"
title: "Hugo Blog Template for GitHub Pages"
canonifyurls: true
